# These are supported funding model platforms

github: # madilraza
patreon:  madilraza
open_collective:  Muhammad Adil Raza Malik
ko_fi: madilraza
tidelift:  npm/babel
community_bridge: cloud-foundry
liberapay:  madilraza
issuehunt:  madilraza
otechie: madilraza
custom:   ['https://github.com/users/madilraza/projects/3', 'https://github.com/users/madilraza/projects/2']
